name: Selenium Tests

on:
  push:
    branches:
      - main  # adjust branch as needed
  pull_request:
    branches:
      - main  # Replace with your branch name    
  schedule:
    - cron: '0 0 * * *'  # Schedule daily at midnight UTC; adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'  

      - name: Set up Microsoft Edge WebDriver
        uses: browser-actions/setup-edge@v1

      - name: Install dependencies
        run: |
          mvn clean install  # Assuming Maven is used for dependency management

      - name: Run Selenium tests
        run: |
          mvn clean test  # Adjust as per your Maven command to run tests
        env:
          CI: true
